apiVersion: v1
kind: Service
metadata:
  name: minesite
spec:
  ports:
  - port: 80
    targetPort: 1500
  selector:
    app: minesite
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minesite
spec:
  selector:
    matchLabels:
      app: minesite
  replicas: 1
  template:
    metadata:
      labels:
        app: minesite
    spec:
      containers:
      - name: minesite
        image: debian
        command: [ "/bin/bash", "-c", "--" ]
        args:
          - |
            apt update -y
            apt install netcat-openbsd -y
            echo '<!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="UTF-8">
              <title>Teh Joker Minecraft Server</title>
              <style>
                body { background-color: #111; color: #0f0; font-family: monospace; padding: 40px; text-align: center; }
                h1 { font-size: 48px; }
                p { font-size: 20px; }
              </style>
            </head>
            <body>
              <h1>🎮 Teh Joker Minecraft Server 🎮</h1>
              <p>IP: <strong>server.tehjoker.com</strong></p>
              <p>Port: <strong>19132</strong></p>
              <p>Join us for chaos, creepers, and clowns 🤡</p>
            </body>
            </html>' > index.html
            while true; do { echo -e 'HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n'; cat index.html; } | nc -l -q 0 0.0.0.0 1500; done
        ports:
        - containerPort: 1500
