apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - whatmovie.tehjoker.com
    - exotics.tehjoker.com
    - chain.tehjoker.com
    - mine.tehjoker.com
    secretName: joker-tls
  rules:
  - host: "whatmovie.tehjoker.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: whatmovie
            port:
              number: 80
  - host: "exotics.tehjoker.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: exotics
            port:
              number: 80
  - host: "chain.tehjoker.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: chain
            port:
              number: 80
  - host: "mine.tehjoker.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: minesite
            port:
              number: 80
  ingressClassName: nginx

